(function($){var transitionSpeedMs=500;var searchAnimationFinished=1;const mobileMenuActiveHiddenElements='#fl-main-content, .block-container';jQuery('#header_main_row .pp-search-form__submit').click(function(event){if(!jQuery('#header_main_row').hasClass('expanded-search')){event.preventDefault();if(searchAnimationFinished){searchAnimationFinished=0;jQuery('#header_main_row').addClass('expanded-search');jQuery('.pp-search-form__input').focus();setTimeout(function(){searchAnimationFinished=1;},transitionSpeedMs);}}
else if(jQuery('.pp-search-form__input').val()==""){event.preventDefault();if(searchAnimationFinished){searchAnimationFinished=0;jQuery('#header_main_row').removeClass('expanded-search');setTimeout(function(){searchAnimationFinished=1;},transitionSpeedMs);}
else{jQuery('.pp-search-form__input').focus();}}});jQuery('.fl-menu-mobile-toggle.hamburger').click(function(event){if(jQuery(this).hasClass('fl-active')||jQuery('body').hasClass('mobile-searching')){if(jQuery('body').hasClass('mobile-searching')){event.preventDefault();event.stopPropagation();jQuery('body').removeClass('mobile-menu-open mobile-searching');jQuery('#header_mobile_main_row .fl-menu-mobile-toggle.hamburger').removeClass('fl-active');}
else{jQuery('.phantom-menu').addClass('willClose');this
jQuery('body').removeClass('mobile-menu-open');setTimeout(function(){jQuery('.phantom-menu').removeClass('active willClose');},transitionSpeedMs);}
jQuery(mobileMenuActiveHiddenElements).fadeIn();jQuery('footer').fadeIn();}
else{jQuery('body').addClass('mobile-menu-open');jQuery(mobileMenuActiveHiddenElements).fadeOut();jQuery('footer').fadeOut();}});jQuery('body').on('change','#give-ffm-section select',function(){var selectElement=jQuery(this);var selectValue=selectElement.val();setTimeout(function(){if(selectElement.data('type')=='select'){if(selectValue){selectElement.val(selectValue);}else{selectElement.val('');}}},1);});$(window).scroll(function(){var scroll=$(window).scrollTop();if(scroll>400){$(".page").addClass("scrolled");}
else{$(".page").removeClass("scrolled");}});jQuery('.product_quantity_chooser .plus').click(function(){var newVal=+jQuery('.product_quantity_chooser .qty_val').val()+1;jQuery('.product_quantity_chooser .qty_val').val(newVal);});jQuery('.product_quantity_chooser .minus').click(function(){var newVal=+jQuery('.product_quantity_chooser .qty_val').val()-1;if(newVal>0)jQuery('.product_quantity_chooser .qty_val').val(newVal);});$(document).ready(function(){jQuery('.archive.tax-product_cat .orderby').select2({placeholder:"Select a state"});var lastScrollTop=$(window).scrollTop();$(window).scroll(function(){var scroll=$(window).scrollTop();if(scroll>=500&&$(window).width()>991){if(scroll>lastScrollTop){$(".top_banner_strip").addClass("conceal");}
else{$(".top_banner_strip").removeClass("conceal");}}
else{$(".top_banner_strip").removeClass("conceal");}
lastScrollTop=scroll<=0?0:scroll;});jQuery('body:not(.fl-builder-edit) .mobile-menu-search-wrapper').click(function(event){event.stopPropagation();});jQuery('#header_mobile_main_row  .mobile-menu-search-icon').click(function(event){event.stopPropagation();jQuery('body').addClass('mobile-menu-open mobile-searching');jQuery(mobileMenuActiveHiddenElements).fadeOut();jQuery('footer').fadeOut();jQuery('#header_mobile_main_row .fl-menu-mobile-toggle.hamburger').addClass('fl-active');jQuery('.mobile-menu-search .pp-search-form__input').focus();});if(jQuery('#header_mobile_main_row').find('.phantom-menu').length===0){var phantomMenuElement="<div class='phantom-menu'><div class='phantom-menu-header'><i class='fas fa-angle-left left-arrow'></i><a class='title' href=''></a></div><div class='content'></div></div>";jQuery(phantomMenuElement).insertAfter("#header_mobile_main_row .fl-menu-mobile-clone");}
jQuery('#menu-mobile-menu .fl-has-submenu').click(function(event){var title=jQuery(".fl-has-submenu-container > a",this).html();var href=jQuery(".fl-has-submenu-container > a",this).attr('href');var submenuContent=jQuery(".sub-menu",this).html();jQuery('.phantom-menu .title').text(title).attr('href',href);jQuery('.phantom-menu .content').html(submenuContent);jQuery('.phantom-menu').addClass('active');});jQuery('.phantom-menu .phantom-menu-header').click(function(event){event.stopPropagation();});jQuery('.phantom-menu .left-arrow').click(function(event){event.stopPropagation();jQuery('.phantom-menu').removeClass('active');jQuery('.fl-menu-mobile-toggle').addClass('fl-active');});jQuery(".pp-accordion-item").each(function(){var content=jQuery(this).find(".pp-accordion-content");if(!content.text().trim().length){jQuery(this).hide();}});var tab_counter=0;jQuery(".uabb-content-wrap").find(".section").each(function(){if(!jQuery(this).find(".uabb-content").text().trim().length){jQuery("li[data-index='"+tab_counter+"']").hide();}
tab_counter++;});var index=0;jQuery(".uabb-tabs-nav li").each(function(){if(jQuery(this).hasClass("uabb-tab-current")&&jQuery(this).css("display")=="block"){return false;}
if(jQuery(this).hasClass("uabb-tab-current")&&jQuery(this).css("display")=="none"){jQuery(this).toggleClass("uabb-tab-current");}
if(!jQuery(this).hasClass("uabb-tab-current")&&jQuery(this).css("display")=="block"){jQuery(this).toggleClass("uabb-tab-current");index=jQuery(this).attr("data-index");return false;}});jQuery(".uabb-content-wrap div").each(function(){jQuery(this).removeClass("uabb-content-current");});if(jQuery("#section-simple-"+index).length){if(!jQuery("#section-simple-"+index).hasClass("uabb-content-current")){jQuery("#section-simple-"+index).addClass("uabb-content-current");}}
jQuery('[id^="section-simple-"]').each(function(){if(!jQuery(this).find('.uabb-content').text().trim().length){jQuery(this).hide();}
jQuery(this).find('.uabb-acc-icon').css('lineHeight','1em');jQuery(this).on('click',function(){jQuery(this).find('.uabb-acc-icon').toggleClass('opened-content');});});jQuery(".pp-tabs-labels").find(".pp-tabs-label").each(function(){var time_tab=jQuery(this);var data_index=time_tab.attr("data-index");if(jQuery("#exhibition-tab-"+(parseInt(data_index)+1)+"-content").length&&!jQuery("#exhibition-tab-"+(parseInt(data_index)+1)+"-content").text().trim().length){jQuery(time_tab).hide();}});var time_tab_index=0;jQuery(".pp-tabs-labels").find(".pp-tabs-label").each(function(){if(jQuery(this).hasClass("pp-tab-active")&&jQuery(this).css("display")=="block"){return false;}
if(jQuery(this).hasClass("pp-tab-active")&&jQuery(this).css("display")=="none"){jQuery(this).toggleClass("pp-tab-active");}
if(!jQuery(this).hasClass("pp-tab-active")&&jQuery(this).css("display")=="block"){jQuery(this).toggleClass("pp-tab-active");time_tab_index=jQuery(this).attr("data-index");return false;}});if(time_tab_index>0){jQuery(".pp-tabs-panels").find(".pp-tabs-panel-content").each(function(){jQuery(this).removeClass("pp-tab-active");});if(jQuery("#exhibition-tab-"+(parseInt(time_tab_index)+1)+"-content").length){if(!jQuery("#exhibition-tab-"+(parseInt(time_tab_index)+1)+"-content").hasClass("pp-tab-active")){jQuery("#exhibition-tab-"+(parseInt(time_tab_index)+1)+"-content").addClass("pp-tab-active");}}}
jQuery('.facebook_share_button').wrap(function(){return '<a href="'+jQuery('.facebook_share_button').find('a').attr('href')+'" target="_blank"></a>';});jQuery('.twitter_share_button').wrap(function(){return '<a href="'+jQuery('.twitter_share_button').find('a').attr('href')+'" target="_blank"></a>';});jQuery('.email_share_button').wrap(function(){return '<a href="'+jQuery('.email_share_button').find('a').attr('href')+'" target="_blank"></a>';});if(jQuery('.about_us_info').length){var showChar=1750;jQuery('.about_us_info').children().last().append('<span class="morelink less">...read less</span>');var content=jQuery('.about_us_info').html();if(content.length>showChar){jQuery('.about_us_info').html(content.substr(0,showChar)+'<span class="morelink">...read more</span>');jQuery('body').on('click','.morelink',function(){if(jQuery(this).hasClass('less')){jQuery('.about_us_info').html(content.substr(0,showChar)+'<span class="morelink">...read more</span>');}
else{jQuery('.about_us_info').html(content);}
return false;});}}
jQuery('.affinity-group-content').each(function(){var af_content=jQuery(this);var showChar=500;var all_benefits='<span class="see-all-benefits">See All Benefits</span>';var content=af_content.html();if(content.length>showChar){var trimmedString=content.substr(0,showChar);trimmedString=trimmedString.substr(0,Math.min(trimmedString.length,trimmedString.lastIndexOf(" ")));af_content.html(trimmedString+'...');jQuery(all_benefits).insertAfter(this);af_content.siblings('.see-all-benefits').click(function(){if(jQuery(this).hasClass('less')){jQuery(this).removeClass('less');jQuery(this).text('See All Benefits');af_content.html(trimmedString+'...');}
else{jQuery(this).addClass('less');jQuery(this).text('See Less Benefits');af_content.html(content);}
return false;});}});var modal=document.getElementById('myModal');if(typeof(modal)!='undefined'&&modal!=null){var img=document.getElementById('expandableImage');var imgDescription=document.getElementById('expandableImageDescription');var expandImg=document.getElementById('expandImage');var modalImg=document.getElementById('modalExpandableImage');var captionText=document.getElementById('caption');var closeButton=document.getElementsByClassName('close')[0];expandImg.onclick=function(){modal.style.display='block';modalImg.src=img.src;captionText.innerHTML=imgDescription.innerHTML;}
closeButton.onclick=function(){modal.style.display='none';}
document.onkeydown=function(e){e=e||window.event;if(e.keyCode==27&&modal.style.display=='block'){modal.style.display='none';}}}
jQuery('.cart-contents, .mini-cart-header').hover(function(){jQuery('.mini-cart-header').toggleClass('show');});var container='';jQuery('#fl-main-content').find('.fl-row').each(function(){if(jQuery(this).find('.gutenberg-full-width-image-container').length){container=jQuery(this);}});if(container.length){var sideBySideImages=jQuery('.gutenberg-full-width-side-by-side-images');var leftColumn=jQuery('.gutenberg-full-width-left-column-image');var rightColumn=jQuery('.gutenberg-full-width-right-column-image');var leftColumnImg=jQuery('.gutenberg-full-width-left-column-image img');var rightColumnImg=jQuery('.gutenberg-full-width-right-column-image img');var watchSideBySideImages=_.throttle(function(){var containerWidth=Math.abs(jQuery(container).css('width').replace(/\D/g,''));var containerPaddingLeft=Math.abs(jQuery(container).css('padding-left').replace(/\D/g,''));var bodyWidth=Math.abs(jQuery('body').css('width').replace(/\D/g,''));var marginLeft=((bodyWidth-containerWidth)/2)+containerPaddingLeft;jQuery(sideBySideImages).css('position','relative');jQuery(sideBySideImages).css('marginLeft',-marginLeft+'px');jQuery(sideBySideImages).css('width',bodyWidth+'px');jQuery(leftColumn).css('width',(bodyWidth/2)+'px');jQuery(rightColumn).css('width',(bodyWidth/2)+'px');jQuery(leftColumn).find('img').css('maxHeight',(bodyWidth/3)+'px');jQuery(rightColumn).find('img').css('maxHeight',(bodyWidth/3)+'px');jQuery(leftColumnImg).css('width',(bodyWidth/2)+'px');jQuery(rightColumnImg).css('width',(bodyWidth/2)+'px');},100);jQuery(window).on('load resize',function(){watchSideBySideImages();});}
$('.section:not(.uabb-content-current)').find('.uabb-acc-icon').toggleClass('opened-content');jQuery('.my-membership-detail-user-membership-actions').on('click','.button.cancel',function(e){e.stopImmediatePropagation();return confirm('Are you sure that you want to cancel your membership?');});});jQuery('.content_tab_titles_container .title').click(function(){if(jQuery(this).hasClass('active'))return;else{jQuery('.content_tab_titles_container .title').removeClass('active');jQuery(this).addClass('active');const id=jQuery(this).data('tab-id');jQuery('.content_tab').removeClass('visible');jQuery('#'+id).addClass('visible');}});jQuery('.project_slides .arrow').click(function(){const slidesPerPage=4;if(jQuery(this).hasClass('right')){if(jQuery('.project_slides .slide:not(.hide)').length>slidesPerPage){jQuery('.project_slides .slide:not(.hide):first').addClass('hide');}}
else if(jQuery(this).hasClass('left')){jQuery('.project_slides .slide.hide:last').removeClass('hide');}
if(jQuery('.project_slides .slide:not(.hide)').length==slidesPerPage){jQuery('.project_slides .arrow.right').addClass('inactive');}
else jQuery('.project_slides .arrow.right').removeClass('inactive');if(jQuery('.project_slides .slide.hide').length==0){jQuery('.project_slides .arrow.left').addClass('inactive');}
else jQuery('.project_slides .arrow.left').removeClass('inactive');});jQuery(document).ready(function(){jQuery(".support-menu-item").on("hover",function(){jQuery(jQuery(".support-menu-item").find('ul')[0]).css('width','1200px');});jQuery("*:contains('Showing 1-0 of 0')").last().html('Showing 0-0 of 0');});$(document).ready(function(){$('.dropbtn-category').click(function(){var $dropdown=$(this).parent();$dropdown.find('.dropdown-content').toggle();});});(function(document,history,location){var HISTORY_SUPPORT=!!(history&&history.pushState);var anchorScrolls={ANCHOR_REGEX:/^#[^ ]+$/,init:function(){this.scrollToCurrent();$(window).on('hashchange',$.proxy(this,'scrollToCurrent'));$('body').on('click','a',$.proxy(this,'delegateAnchors'));},getFixedOffset:function(){return $('header').height();},scrollIfAnchor:function(href,pushToHistory){var match,anchorOffset;if(!this.ANCHOR_REGEX.test(href)){return false;}
match=document.getElementById(href.slice(1));if(match){anchorOffset=$(match).offset().top-this.getFixedOffset();$('html, body').animate({scrollTop:anchorOffset});if(HISTORY_SUPPORT&&pushToHistory){history.pushState({},document.title,location.pathname+href);}}
return!!match;},scrollToCurrent:function(e){if(this.scrollIfAnchor(window.location.hash)&&e){e.preventDefault();}},delegateAnchors:function(e){var elem=e.target;if(this.scrollIfAnchor(elem.getAttribute('href'),true)){e.preventDefault();}}};$(document).ready($.proxy(anchorScrolls,'init'));})(window.document,window.history,window.location);$(document).ready(function(){$('.slideshow-nav br').remove();var productPrices=$(".product-price").find(".woocommerce-Price-amount");if(productPrices.length==2){if(productPrices[0].innerHTML===productPrices[1].innerHTML){$(productPrices[0]).remove();}}});})(jQuery);jQuery(function($){if(!String.prototype.getDecimals){String.prototype.getDecimals=function(){var num=this,match=(''+num).match(/(?:\.(\d+))?(?:[eE]([+-]?\d+))?$/);if(!match){return 0;}
return Math.max(0,(match[1]?match[1].length:0)-(match[2]?+match[2]:0));}}
$(document.body).on('click','.plus, .minus',function(){var $qty=$(this).closest('.quantity').find('.qty'),currentVal=parseFloat($qty.val()),max=parseFloat($qty.attr('max')),min=parseFloat($qty.attr('min')),step=$qty.attr('step');if(!currentVal||currentVal===''||currentVal==='NaN')currentVal=0;if(max===''||max==='NaN')max='';if(min===''||min==='NaN')min=0;if(step==='any'||step===''||step===undefined||parseFloat(step)==='NaN')step=1;if($(this).is('.plus')){if(max&&(currentVal>=max)){$qty.val(max);}else{$qty.val((currentVal+parseFloat(step)).toFixed(step.getDecimals()));}}else{if(min&&(currentVal<=min)){$qty.val(min);}else if(currentVal>0){$qty.val((currentVal-parseFloat(step)).toFixed(step.getDecimals()));}}
$qty.trigger('change');});$(document.body).on('click','.plus-icon, .minus-icon',function(){var qty=$('input[name="quantity"]');var button_qty=$(this).parent().next();qty.attr('value',qty.val());button_qty.data('quantity',qty.val());});});jQuery(function($){$('.fl-builder-pagination a.page-numbers').each(function(idx,el){const isFirstPageLink=el.href.indexOf('paged-3')===-1;if(isFirstPageLink){const newFirstPageURL=el.href.replace('/product-category','');el.href=newFirstPageURL;return;}
const hasProductCatAlready=el.href.indexOf('product-category')>-1;if(hasProductCatAlready){return;}
const urlArray=el.href.split('/');urlArray.splice(3,0,'product-category');const newURL=urlArray.join('/');el.href=newURL;});});jQuery(function($){$(document).ready(function(){var hashProvided=$(location).attr('hash');if(hashProvided){let membershipDivs=jQuery(".product_title.entry-title");membershipDivs.each(function(){if(jQuery(this).is(":visible")){let divName=(jQuery(this)[0].innerHTML).toLowerCase();divName="#"+divName.replace(/ .*/,'');if(hashProvided==divName){let scrollPosition=jQuery(this).offset().top;if(window.matchMedia("(max-width: 767px)").matches)
scrollPosition-=400;else
scrollPosition-=200;console.log(scrollPosition);jQuery('html, body').animate({scrollTop:scrollPosition},500);}}});};});$(document.body).on('click','.menu-button-membership',function(e){var pathName=$(location).attr('pathname').replace(/[/]+/g,"");if(pathName=='membership'){console.log(pathName);e.preventDefault();window.location.replace(jQuery(this).find('a')[0].href);location.reload(true);}});});