(function($){if('undefined'===typeof wc_add_to_cart_params){return false;}
$('body').delegate('.woopack-product-quick-options','click',function(e){e.preventDefault();e.stopPropagation();var nodeId=$(this).parents('.fl-module').attr('data-node');var product=$(this).parents('.product'),productId=product.data('product-id');new WooPackModal({source:'ajax',ajaxUrl:woopack_config.ajaxurl,ajaxData:{action:'woopack_product_quick_view',node_id:nodeId,product_id:productId},breakpoint:767,cssClass:'woopack-modal-'+nodeId,onAjaxLoad:function(wrapper){if(wrapper.find('.woopack-modal-inner').height()>=window.innerHeight){wrapper.find('.woopack-modal-inner').css({'max-height':(window.innerHeight-60)+'px',});wrapper.find('.woopack-modal-inner .woopack-modal-content').css({'height':(window.innerHeight-80)+'px','overflow-y':'auto'});}
wrapper.find('.woocommerce-product-gallery .woocommerce-product-gallery__image a').on('click',function(e){e.preventDefault();e.stopPropagation();var imageEl=$(this).parents('.woocommerce-product-gallery__image');var firstEl=imageEl.parents('.woocommerce-product-gallery').find('.woocommerce-product-gallery__image:first');imageEl.insertBefore(firstEl);});setTimeout(function(){if(typeof $.fn.wc_variation_form!=='undefined'){if(wrapper.find('form.variations_form').length>0){wrapper.find('form.variations_form').wc_variation_form();}}
wrapper.find('.product-type-external form.cart').attr('target','_blank');},100);},onClose:function(wrapper){wrapper.removeClass('woopack-modal-'+nodeId);}});});$(window).on('resize',function(){if(window.innerWidth>767){$('.woopack-modal .woopack-modal-inner').css({height:'auto'});}});$('body').delegate('.woopack-qty-input input.qty','change keyup blur',function(){var qty=parseInt($(this).val());qty=(0===qty||''===qty)?1:qty;$(this).val(qty);$(this).parents('.woopack-product-action').find('a.button').attr('data-quantity',qty);});$('body').delegate('.woopack-modal form.cart, .woopack-single-product form.cart','submit',function(e){if($(this).hasClass('variations_form')&&typeof $.fn.wc_variation_form==='undefined'){return;}
if($(this).parents('.product-type-external').length>0){return;}
e.preventDefault();e.stopPropagation();var form=$(this);var grouped=$(this).hasClass('grouped_form');var $thisbutton=$(this).find('button[type="submit"]');if(grouped){$(this).find('.woocommerce-grouped-product-list tr').each(function(){var qty=$(this).find('input.qty').val();var productId=$(this).attr('id').split('-')[1];if(qty>0){var data={'quantity':qty,'product_id':productId,};$thisbutton.removeClass('added');$thisbutton.addClass('loading');$(document.body).trigger('adding_to_cart',[$thisbutton,data]);addToCart($thisbutton,data);}});}else{if($(this).find('input[name="variation_id"]').length>0){handleVariationForm($(this));}else{var data={'action':'woopack_add_to_cart','quantity':$(this).find('.qty').val(),'product_id':$(this).find('.single_add_to_cart_button').val(),};if(form.find('.wc-bookings-booking-form').length>0){data.product_id=form.find('.wc-booking-product-id').val();data["wc_bookings_field_start_date_month"]=form.find('input[name="wc_bookings_field_start_date_month"]').val();data["wc_bookings_field_start_date_day"]=form.find('input[name="wc_bookings_field_start_date_day"]').val();data["wc_bookings_field_start_date_year"]=form.find('input[name="wc_bookings_field_start_date_year"]').val();data["wc_bookings_field_start_date_time"]=form.find('input[name="wc_bookings_field_start_date_time"]').val();data["wc_bookings_field_start_date_local_timezone"]=form.find('input[name="wc_bookings_field_start_date_local_timezone"]').val();data["wc_bookings_field_duration"]=form.find('input[name="wc_bookings_field_duration"]').val();data["start_time"]=form.find('[name="start_time"]').val();data["end_time"]=form.find('[name="end_time"]').val();}
$thisbutton.removeClass('added');$thisbutton.addClass('loading');$(document.body).trigger('adding_to_cart',[$thisbutton,data]);addToCart($thisbutton,data);}}});$('body').delegate('.woopack-products .product .variations_form, .woopack-product-add-to-cart .variations_form','submit',function(e){if(typeof wc_add_to_cart_params==='undefined'){return;}
e.preventDefault();e.stopPropagation();handleVariationForm($(this));});$('body').delegate('.woopack-products .product .grouped_form','submit',function(e){e.preventDefault();e.stopPropagation();var $thisbutton=$(this).find('button[type="submit"]');$(this).find('.woocommerce-grouped-product-list tr').each(function(){var qty=$(this).find('input.qty').val();var productId=$(this).attr('id').split('-')[1];if(qty>0){var data={'quantity':qty,'product_id':productId,};$thisbutton.removeClass('added');$thisbutton.addClass('loading');$(document.body).trigger('adding_to_cart',[$thisbutton,data]);addToCart($thisbutton,data);}});});var handleVariationForm=function($form){var data={'action':'woopack_add_to_cart','quantity':$form.find('.qty').val(),'product_id':$form.find('input[name="product_id"]').val(),'variation_id':$form.find('input[name="variation_id"]').val(),};var variations=$form.data('product_variations')[0];var attributes=[];if('undefined'!==typeof variations.attributes){Object.keys(variations.attributes).map(function(attr){if($form.find('[name="'+attr+'"]').length>0){var attr_string=attr+'|'+$form.find('[name="'+attr+'"]').val();attributes.push(attr_string);}});data['variation']=attributes;}
var $thisbutton=$form.find('button[type="submit"]');$thisbutton.removeClass('added');$thisbutton.addClass('loading');$(document.body).trigger('adding_to_cart',[$thisbutton,data]);addToCart($thisbutton,data);};var addToCart=function($thisbutton,data){var url=wc_add_to_cart_params.wc_ajax_url.toString().replace('%%endpoint%%','add_to_cart');if(typeof data.action!=='undefined'){url=woopack_config.ajaxurl;}
$.post(url,data,function(response){if(!response){return;}
if(response.error&&response.product_url){window.location=response.product_url;return;}
if(wc_add_to_cart_params.cart_redirect_after_add==='yes'){window.location=wc_add_to_cart_params.cart_url;return;}
$(document.body).trigger('added_to_cart',[response.fragments,response.cart_hash,$thisbutton]);});};$('body').delegate('.woopack-products .product .variations_form select, .woopack-single-product .variations_form select','change',function(){var $this=$(this),attr=$this.attr('name'),val=$this.val(),form=$this.parents('.variations_form');if($this.parents('.woopack-product-grid.product').length>0){var img=$this.parents('.woopack-product-grid.product').find('.woopack-product-image img');}else{var img=$this.parents('.woopack-single-product').find('.single-product-image img');}
var variations=form.data('product_variations');if(!variations){return;}
variations.forEach(function(item){if('undefined'!==typeof item.attributes[attr]&&val===item.attributes[attr]){if('undefined'!==typeof item.image){img.attr('src',item.image.thumb_src);img.attr('srcset',item.image.srcset);}
if('undefined'!==typeof item.variation_id){form.find('input[name="variation_id"]').val(item.variation_id);}}});});$(document).on('wc_cart_button_updated',function(e,button){button.parent().find('a.added_to_cart').addClass('button alt');});var w=$('.woopack-product-image').find('.woopack-product-featured-image').attr('width');$('.woopack-product-image').find('.woocommerce-placeholder.wp-post-image').width(w);})(jQuery);