<!--# (APPENDIX) Appendix {-}-->

# Reading their future {#sampling}

It's very easy to overlook mistakes in your own writing. That's true of any written communication such as a covering letter, personal statement, email or message that you write. Overlooked mistakes are particularly common in CVs (or resumes) because you can spend *hours* carefully honing the words and the formatting but not see a fatal error at the top of page one.

## Debug their CV

There's at leat three solutions to this problem:

1. [dogfooding](#dogfooding) we've already talked about, read your work ALOUD
1. “I'll show you mine if you show me yours.”
    + Debug a friends or peers CV by swapping with them.
1. Debug the fictitious CVs below

So, here are some fictitious CVs for you to debug, from students of Computer Science. They are based on CVs I've seen, warts and all, with personal information removed and anonymised. Can you spot their triumphs and tragedies? Can you debug their CV against the sample job description at CoolTech below? Can you find their future?

Special thanks to [Toby Howard](https://en.wikipedia.org/wiki/Toby_Howard) and [Sean Bechhofer](https://personalpages.manchester.ac.uk/staff/sean.bechhofer/) for coming up with some of these names. Please direct any complaints about the terrible geeky puns to Toby and Sean! Thanks also Ben Carter and Penny Gordon Lanes in the careers service at the University of Manchester, some of these CVs are based on examples they have collected and anonymised. 🙏

## Breakpoints

Some [breakpoints](https://en.wikipedia.org/wiki/Breakpoint) for discussion, when you read these CVs make a note of:

1. **What Went Well?** (WWW) What do you like about any given CV, what have they done well?
1. **Even Better If?** (EBI) What could be improved
1. **Their Rank** Who is top of your list to interview? Who is going in the bin and why?

Imagine the person is real, what would you tell them about their CV if they'd given it to you for advice without hurting their feelings?

## Sample CVs

### Penelope Tester {#pen-tester}

Penny Tester, or Pen as her friends call her, loves cybersecurity and reverse engineering. She has a real passion for finding vulnerabilities in software and hardware. Just don't call her a *hacker*, she hates that horribly overloaded word.

See [cdyf.me/Penelope_Tester.pdf](https://www.cdyf.me/Penelope_Tester.pdf)

### Rick Urshion {#rick-urshion}

Rick is a big fan of functional programming and loves expressing himself using languages like Lisp, Haskell, Clojure, Erlang and Scala. He really hates side-effects but tries to avoid getting into a state about it. His critics say he can be inefficient but Rick insists he's just lazy.

See [cdyf.me/Rick_Urshion.pdf](https://www.cdyf.me/Rick_Urshion.pdf)

### Marge Conflict {#marge-conflict}

Marge loves version control and her superpower is resolving people's differences.

*(Marge is currently working on her CV)*

### Michael Rokernel {#mike-rokernel}

Mike loves operating systems, but not if they get too bloated.

See [cdyf.me/Mike_Rokernel.pdf](https://www.cdyf.me/Mike_Rokernel.pdf)

### Florence Ting-Point {#flo-ting-point}

Flo loves maths and is a particularly big fan of [floating-point arithmetic](https://en.wikipedia.org/wiki/Floating-point_arithmetic).

See [cdyf.me/Flo_Ting-Point.pdf](https://www.cdyf.me/Flo_Ting-Point.pdf)

### Peter Byte {#peter-byte}

Peter and his twin sister Peta, both love big data, machine learning, statistics, data science and Artificial Intelligence (AI). They come from a big family with nine siblings, Deca, Hector, Kilo, Mega, Giga, Terry, Exa, Zita and Yotta. They are wildly ambitious, but critics say the Byte family have been terribly over-hyped.

See [cdyf.me/Peter_Byte.pdf](https://www.cdyf.me/Peter_Byte.pdf)

### Polina Morphism {#polly-morphism}

Polly loves object-oriented programming. She has lots of siblings, and a cousin called, Isa.

*(Polina is currently working on her CV)*

### Neil Pointer {#neil-pointer}

Neil is a mature student who loves the C programming language. The Pointer family are sometimes misunderstood, but Neil compensates for this with his excellent memory management skills and efficiency. He has a younger half-brother, Neil Pointer-Exception, from his fathers second marriage. Neil Pointer-Exception prefers Java  

See [cdyf.me/Neil_Pointer.pdf](https://www.cdyf.me/Neil_Pointer.pdf)

### Bryn Hanby-Roberts {#bryn}

The last CV is a real one. Bryn kindly gave his permission to share it with you. He graduated in 2016, his CV is longer as he has five years of experience under his belt but it provides a useful counterpoint to the examples above.

See [cdyf.me/bryn.pdf](https://www.cdyf.me/bryn.pdf) a snapshot taken in 2021 from [bryn.co.uk](http://bryn.co.uk)

Thanks Bryn. 🙏


## Sample CoolTech Job advert {#cooltech}

We’re looking for bright and geeky graduates to join our software engineering team. No experience is required, and many of our successful applicants have never programmed before. If you think logically and enjoy problem solving, then you have the potential to become a great developer.

A career at CoolTech will challenge you every day. In your first few weeks you will be solving real-world problems as you help to develop software used by professionals across the world.

You’ll be part of an agile development team, working on one of the largest real-time databases in the world. You’ll work on a wide variety of projects, ranging from Artificial Intelligence assisting clinicians with early diagnosis of cancer to an iOS app helping patients manage their diabetes.

Developers at CoolTech are involved in the full software cycle, and work closely with all teams across the company to scope out new projects as they design, develop and deploy our products.






<!-- suggestions from toby

Alex Hacker

Bobby Tables

Justine Time

Gemma Over (friends call her Gem Over)

Dick Claration

Ian Tejer

Ceaser Craplanguage-->
