# Coding your future podcast {#podcast}

This podcast features interviews with student as they come to end of their undergraduate degree or shortly after they graduate. We interview students to find out more about their journey from student to professional. During the interview, we ask students to tell us:

* What's their story? Tell us about themselves
* How did they got into Computer Science
* Which organisation they were employed by, why and how did they chose them
* Tell us about their role in the organisation
* How did they find the job and what other jobs did they look for?
* What was the most enjoyable or rewarding part of working for their employer
* What advice would they give to students looking for placements
* What are their plans for the future
* What’s the most interesting thing happening in computer science / technology right now?
* What are their favourite work related radio shows or podcasts?

## Episode 1: Raluca Cruceru

Interview with Raluca Cruceru [linkedin.com/in/raluca-cruceru/](https://www.linkedin.com/in/raluca-cruceru/), a software engineer at [CERN](https://home.cern/), will be published here shortly. Raluca graduated with BSc in Human Computer Interaction with Industrial Experience in 2020.


## Episode 2: George Dunning

Upcoming interview with George Dunning, software engineer at [steama.co](https://steama.co/) will be published here. George graduated with a BSc in Computer Science with Industrial Experience in 2020.


## Episode 3: It could be you!

If you'd like to be interviewed, get in touch.
