# Hearing your future {#hearing}

This podcast features interviews with students as they come to end of their undergraduate degree or shortly after they graduate. We interview students to find out more about their journey from student to professional. During the interview, we ask students:

## What's your story, coding glory? {#wyscg}
* Tell us a bit about you and where you come from
* Why did you choose to study computer science?
* Which organisation were you employed by, why and how did you choose them
* Tell us about your role in the organisation
* How did you find the job and what other jobs did they look for?
* What was the most enjoyable or rewarding part of working for your employer
* What was the hardest part of finding employment and how did you overcome it
* Advice to your former self, what would you tell yourself in first and second year now that you are older and wiser?
* What did you do for your final year project?
* What comes next?

## Minority report {#minority}
* If you are a member of a minority group, what has your experience been at University and in the workplace
* What can universities (and employers) do to make campuses (and workplaces) more welcoming for members of your minority group?

## One tune, one podcast and one film {#otopof}

There are far too many gratuitous musical references in *Coding your Future* it’s mostly [DadRock](https://www.esquire.com/entertainment/music/a29419783/what-is-dad-rock/) and other antique pieces. [@dadrock] So can you recommend us:

* One tune to rejuvenate and freshen up our playlist. Why is it important to you? Perhaps it’s a tune that makes you relax, feel happy, comforted, reminds you of home, family, friends etc
* One podcast you’ve enjoyed to that you’d recommend our listeners subscribe to
* One film we’ve got to go and watch right now


## Episode 1: Raluca Cruceru

Interview with Raluca Cruceru [careers.cern/Raluca](https://careers.cern/Raluca), a software engineer at [CERN](https://home.cern/), will be published here shortly. Raluca graduated with BSc in Human Computer Interaction with Industrial Experience in 2020.


## Episode 2: George Dunning

Upcoming interview with George Dunning, software engineer at [steama.co](https://steama.co/) in Manchester will be published here. George graduated with a BSc in Computer Science with Industrial Experience in 2020.


## Episode 3: It could be you!

If you'd like to be interviewed, get in touch.
