# Actioning your future {#actioning}

A good technique for describing and emphasising what you have done is to lead with the verbs listed in this chapter. This emphasises what you have *actually done* rather than what you *know*. See the [verbs first](#verbsfirst) section of the [debug your future](debugging.html) chapter.

## Breakpoints

Before you start, here are some [breakpoints](https://en.wikipedia.org/wiki/Breakpoint) for you to pause and consider. Quickly scan your CV, covering letter or application form for the verbs listed in this chapter:

* Are there any verbs that are missing?
* Do you need to increase the variety of verbs you have used?
* Have you over-used certain verbs (like *worked* or *assisted* for example)
* Are their any verbs you can't provide evidence of, such as leadership?
* What activities or projects could you do to that would provide better evidence you have these skills?

## Team verbs {#joining}

Some verbs to demonstrate how you have worked and communicated with others in a team.

* administered
* advised
* assisted
* coached
* encouraged
* instructed
* interviewed
* organised
* participated
* presented
* recommended
* recruited
* suggested
* volunteered


## Engineering verbs {#engineering}

Verbs to demonstrate your engineering and technical skills.

* added (e.g. new features)
* analysed (e.g. the requirements)
* architected
* assigned (e.g. bugs to team members)
* automated (e.g. builds and tests)
* built
* branched (e.g. git)
* configured
* designed (e.g. [greenfield software development](https://en.wikipedia.org/wiki/Greenfield_project))
* cloned (e.g. git)
* debugged (e.g. [Brownfield development](https://en.wikipedia.org/wiki/Brownfield_(software_development))
* developed
* deployed
* documented
* experimented
* gathered (e.g. requirements)
* implemented (e.g. an algorithm)
* installed
* integrated (e.g. different systems)
* merged (e.g. git)
* migrated
* modified (e.g. game mods)
* specified
* tested

## Leadership verbs {#leading}

Some verbs to demonstrate how you have used your initiative and taken the lead:

* established
* created
* decided
* devised
* directed
* facilitated
* introduced
* launched
* led
* managed
* mentored
* motivated
* supervised


## Improving verbs

Verbs that demonstrate how you have improved a situation by taking resposibility for something:

* delivered
* edited
* enhanced
* generated
* increased
* refined
* resolved
* saved
* transformed

## Scientific verbs

Verbs that demonstrate your analytical and scientific skills

* assessed
* calculated
* discovered
* estimated
* evaluated
* identified
* interpreted
* investigated
* proved
* researched  
* reviewed
* tested

## Winning verbs  {#winning}

Verbs for demonstrating your achievements and honours

* achieved
* attained
* awarded
* nominated
* recommended
* selected
* mastered
* won

## Planning and organisation verbs  {#planning}

Verbs to demonstrate your planning and organisational skills:

* arranged
* prepared
* scheduled
* organised
* planned
* produced
* revised

## Influential verbs  {#influencing}

Verbs that demonstrate how you have influenced and persuaded others:

* guided
* influenced
* liaised
* negotiated
* mediated
* promoted
* presented
* publicised

<!--chapter:end:18-verbsfirst.Rmd-->
