# Scheduling your future {#scheduling}  
This is the schedule for the live (synchronous) sessions for Coding Your Future in 2021 (COMP2CARS), on **Mondays at 1pm on Zoom** where they complement the second year tutorials (COMP2TUT) at the University of Manchester.

As with semester 1, COMP2CARS takes place in the same slot as COMP2TUT when you meet your personal tutor. See the timetable [studentnet.cs.manchester.ac.uk/ugt/timetable](http://studentnet.cs.manchester.ac.uk/ugt/timetable/).

These sessions will revisit themes from semester one if you missed them last semester, we'll also have an open session where we'll tackle whatever issues you need about finding placements and internships during 2021. We'll be meeting at [zoom.us/my/duncanhull](http://zoom.us/my/duncanhull), please sign into zoom with your \@student.manchester.ac.uk account.  

<!--## Monday 8th Feb {#week1}
Depending on your when you meet your tutor

* *Either* COMP2CARS: Debug their CV, see [cdyf.me/sampling.html](https://www.cdyf.me/sampling.html)
* *Or* COMP2TUT: Meet your tutor see [studentnet.cs.manchester.ac.uk/ugt/tutorgroups.php?level=2](http://studentnet.cs.manchester.ac.uk/ugt/tutorgroups.php?level=2)

## Monday 15th Feb {#week2}
Depending on your when you meet your tutor

* *Either* COMP2CARS: Debug their CV, see [cdyf.me/sampling.html](https://www.cdyf.me/sampling.html) repeated session
* *Or* COMP2TUT: Meet your tutor see [studentnet.cs.manchester.ac.uk/ugt/tutorgroups.php?level=2](http://studentnet.cs.manchester.ac.uk/ugt/tutorgroups.php?level=2)-->


## Monday 22nd Feb {#week3}   
* Looking after your future, see [cdyf.me/wellbeing.html](https://www.cdyf.me/wellbeing.html)
<!-- WOOP my life part of mental health-->
<!--also semester 1: are you experienced panel-->
<!--also semester 1: why bother with experience-->

## Monday 1st March {#week4}
* Finding your future, see [cdyf.me/finding.html](https://www.cdyf.me/finding.html): How can you adapt and optimise your job search strategies?

## Monday 8th March {#week5}
Depending on your when you meet your tutor

* *Either* COMP2TUT: Meet your tutor see [studentnet.cs.manchester.ac.uk/ugt/tutorgroups.php?level=2](http://studentnet.cs.manchester.ac.uk/ugt/tutorgroups.php?level=2)
* *OR* COMP2CARS: Writing your future, see [cdyf.me/communicating.html](https://www.cdyf.me/communicating.html)

## Monday 15th March {#week6}  
Depending on your when you meet your tutor

* *Either* COMP2TUT: Meet your tutor see [studentnet.cs.manchester.ac.uk/ugt/tutorgroups.php?level=2](http://studentnet.cs.manchester.ac.uk/ugt/tutorgroups.php?level=2)
* *Or* COMP2CARS: Writing your future (repeated) [cdyf.me/communicating.html](https://www.cdyf.me/communicating.html) and [developers.google.com/tech-writing/one](https://developers.google.com/tech-writing/one)


## Monday 22nd March {#week7}  
* COMP2CARS: Technical writing one (part 2) see [developers.google.com/tech-writing/one](https://developers.google.com/tech-writing/one) and [cdyf.me/communicating.html](https://www.cdyf.me/communicating.html)


## Monday 29th March {#easter}  
* Easter break see [manchester.ac.uk/discover/key-dates/](https://www.manchester.ac.uk/discover/key-dates/)

## Monday 12th April {#week8}  
* to be confirmed

## Monday 19th April {#week9}  
* *Either* COMP2TUT: Meet your tutor see [studentnet.cs.manchester.ac.uk/ugt/tutorgroups.php?level=2](http://studentnet.cs.manchester.ac.uk/ugt/tutorgroups.php?level=2)
* *Or* COMP2CARS:


## Monday 26th April {#week10}  
* *Either* COMP2TUT: Meet your tutor see [studentnet.cs.manchester.ac.uk/ugt/tutorgroups.php?level=2](http://studentnet.cs.manchester.ac.uk/ugt/tutorgroups.php?level=2)
* *Or* COMP2CARS:

## Mon 3rd May  {#week11}  
Early May Bank holiday see [gov.uk/bank-holidays](https://www.gov.uk/bank-holidays)

## Mon 10th May {#week12}  
* So you're going on placement? See [cdyf.me/surviving.html](https://www.cdyf.me/surviving.html)


## Week 13: Monday 17th May {#week13}  

* Semester 2 exams: 19 May–9 June 2021
* Semester 2 ends	11 June 2021
* See [manchester.ac.uk/discover/key-dates/](https://www.manchester.ac.uk/discover/key-dates/)
